main:
    resource: "@nxtcarMainBundle/Controller/MainController.php"
    type:     annotation
    prefix:   /

profile:
    resource: "@nxtcarMainBundle/Controller/ProfileController.php"
    type:     annotation
    prefix:   /

car:
    resource: "@nxtcarMainBundle/Controller/CarController.php"
    type:     annotation
    prefix:   /

ride:
    resource: "@nxtcarMainBundle/Controller/RideController.php"
    type:     annotation
    prefix:   /

FAQ:
    resource: "@nxtcarMainBundle/Controller/FAQController.php"
    type:     annotation
    prefix:   /

car_rests:
    type:     rest
    resource: nxtcar\MainBundle\Controller\Rest\RestCarController

ride_rests:
    type:     rest
    resource: nxtcar\MainBundle\Controller\Rest\RestRideController