<?php

namespace nxtcar\UserBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * @param $user
     * @return array
     */
    public function findPublicQuestions($user)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT comment
                           FROM nxtcarUserBundle:Comment comment
                           JOIN comment.thread thread
                           JOIN nxtcarMainBundle:Ride ride
                           WITH CONCAT('ride_', ride.id) = thread.id
                           WHERE ride.driver = :user
                           AND (comment.author != :user OR comment.author IS NULL)
                           AND comment.createdAt = (SELECT MAX(com.createdAt)
                                                   FROM nxtcarUserBundle:Comment com
                                                   JOIN com.thread thrd
                                                   JOIN nxtcarMainBundle:Ride rid
                                                   WITH CONCAT('ride_', rid.id) = thrd.id
                                                   WHERE rid.driver = :user
                                                   AND (com.author != :user OR com.author IS NULL)
                                                   AND thrd.id = thread.id)
                           ")
            ->setParameter('user', $user)
            ->getResult();
    }
}
