<?php

namespace nxtcar\UserBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * @param $user
     * @return array
     */
    public function findPublicQuestions($user)
    {
        $result = $this->getEntityManager()
            ->createQuery("SELECT comment
                           FROM nxtcarUserBundle:Comment comment
                           JOIN comment.thread thread
                           WHERE thread.id IN (SELECT CONCAT('ride_', rideDate.id)
                                               FROM nxtcarMainBundle:RideDate rideDate
                                               JOIN rideDate.ride ride
                                               WHERE ride.driver = :driver)
                           AND comment.createdAt = (SELECT MAX(cmt.createdAt)
                                                   FROM nxtcarUserBundle:Comment cmt
                                                   JOIN cmt.thread thr
                                                   WHERE thr.id = thread.id
                                                   AND cmt.author != :driver)
                                               ")
            ->setParameter('driver', $user)
            ->getResult();

        return $result;
    }
}
