<?php

namespace nxtcar\UserBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    /**
     * @param $from
     * @param $to
     * @param $rideDate
     * @return array
     */
    public function findPrivateMessages($from, $to, $rideDate)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT msg, fromUser, toUser, rideDate
                           FROM nxtcarUserBundle:Message msg
                           JOIN msg.from fromUser
                           JOIN msg.to toUser
                           JOIN msg.rideDate rideDate
                           JOIN msg.tempRideDate tempRideDate
                           WHERE
                           ((
                               fromUser = :fromUs
                               AND toUser = :toUs
                           )
                           OR (
                               fromUser = :toUs
                               AND toUser = :fromUs
                           ))
                           AND
                           (
                              rideDate = :rideDate
                              OR
                              tempRideDate = :rideDate
                           )

                           ORDER BY msg.sendDate
                           ")
            ->setParameters(array(
                'fromUs' => $from,
                'toUs'  => $to,
                'rideDate' => $rideDate
            ))
            ->getResult();
    }

    /**
     * @param $user
     * @return array
     */
    public function findMessagesByUser($user)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT userFrom, tempRideDate, rideDate
                           FROM nxtcarUserBundle:User userFrom
                           JOIN nxtcarUserBundle:Message message
                           WITH message.from = userFrom
                           LEFT JOIN nxtcarMainBundle:RideDate tempRideDate
                           WITH message.tempRideDate = tempRideDate
                           LEFT JOIN nxtcarMainBundle:RideDate rideDate
                           WITH message.rideDate = rideDate
                           WHERE message.to = :toUs
                           GROUP BY userFrom, tempRideDate, rideDate")
            ->setParameter('toUs', $user)
            ->getResult();
    }
}
