<?php

namespace nxtcar\UserBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    /**
     * @param $from
     * @param $to
     * @param $rideDate
     * @return array
     */
    public function findPrivateMessages($from, $to, $rideDate)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT msg, fromUser, toUser, rideDate
                           FROM nxtcarUserBundle:Message msg
                           JOIN msg.from fromUser
                           JOIN msg.to toUser
                           JOIN msg.rideDate rideDate
                           JOIN msg.tempRideDate tempRideDate
                           WHERE fromUser = :fromUs
                           AND toUser = :toUs
                           AND
                           (
                              rideDate = :rideDate
                              OR
                              tempRideDate = :rideDate
                           )
                           ")
            ->setParameters(array(
                'fromUs' => $from,
                'toUs'  => $to,
                'rideDate' => $rideDate
            ))
            ->getResult();
    }
}
